export const START_FETCHING_PENGAJUAN = "redux/WorkOrder/START_FETCHING_PENGAJUAN";
export const SUCCESS_FETCHING_PENGAJUAN =
  "redux/WorkOrder/SUCCESS_FETCHING_PENGAJUAN";
export const ERROR_FETCHING_PENGAJUAN = "redux/WorkOrder/ERROR_FETCHING_PENGAJUAN";
