export const START_FETCHING_GROUPS = "redux/events/START_FETCHING_GROUPS";
export const SUCCESS_FETCHING_GROUPS = "redux/events/SUCCESS_FETCHING_GROUPS";
export const ERROR_FETCHING_GROUPS = "redux/events/ERROR_FETCHING_GROUPS";
