export const START_FETCHING_CHECKOUTS = "redux/WorkOrder/START_FETCHING_CHECKOUTS";
export const SUCCESS_FETCHING_CHECKOUTS =
  "redux/WorkOrder/SUCCESS_FETCHING_CHECKOUTS";
export const ERROR_FETCHING_CHECKOUTS = "redux/WorkOrder/ERROR_FETCHING_CHECKOUTS";
