export const START_FETCHING_LISTS_DEPARTEMENT =
  "redux/lists/START_FETCHING_LISTS_DEPARTEMENT";
export const SUCCESS_FETCHING_LISTS_DEPARTEMENT =
  "redux/lists/SUCCESS_FETCHING_LISTS_DEPARTEMENT";
export const ERROR_FETCHING_LISTS_DEPARTEMENT =
  "redux/lists/ERROR_FETCHING_LISTS_DEPARTEMENT";

export const START_FETCHING_LISTS_GROUP =
  "redux/lists/START_FETCHING_LISTS_GROUP";
export const SUCCESS_FETCHING_LISTS_GROUP =
  "redux/lists/SUCCESS_FETCHING_LISTS_GROUP";
export const ERROR_FETCHING_LISTS_GROUP =
  "redux/lists/ERROR_FETCHING_LISTS_GROUP";

export const START_FETCHING_LISTS_POSISI =
  "redux/lists/START_FETCHING_LISTS_POSISI";
export const SUCCESS_FETCHING_LISTS_POSISI =
  "redux/lists/SUCCESS_FETCHING_LISTS_POSISI";
export const ERROR_FETCHING_LISTS_POSISI =
  "redux/lists/ERROR_FETCHING_LISTS_POSISI";

export const START_FETCHING_LISTS_ROLES =
  "redux/lists/START_FETCHING_LISTS_ROLES";
export const SUCCESS_FETCHING_LISTS_ROLES =
  "redux/lists/SUCCESS_FETCHING_LISTS_ROLES";
export const ERROR_FETCHING_LISTS_ROLES =
  "redux/lists/ERROR_FETCHING_LISTS_ROLES";