export const START_FETCHING_DEPARTEMENTS =
  "redux/events/START_FETCHING_DEPARTEMENTS";
export const SUCCESS_FETCHING_DEPARTEMENTS =
  "redux/events/SUCCESS_FETCHING_DEPARTEMENTS";
export const ERROR_FETCHING_DEPARTEMENTS =
  "redux/events/ERROR_FETCHING_DEPARTEMENTS";
